use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};
use termy_command_core::{CommandId, KeybindPlatform, default_keybinds_for_platform};
use termy_config_core::{
    AppConfig, ColorSettingId, RootSettingId, SettingsSection, color_setting_specs,
    root_setting_default_value, root_setting_specs,
};

fn main() {
    if let Err(error) = run() {
        eprintln!("{}", error);
        std::process::exit(1);
    }
}

fn run() -> Result<()> {
    let mut args = std::env::args().skip(1);
    let Some(command) = args.next() else {
        bail!(
            "usage: cargo run -p xtask -- <generate-keybindings-doc|generate-config-doc> [--check]"
        );
    };

    let mut check_only = false;
    for arg in args {
        match arg.as_str() {
            "--check" => check_only = true,
            other => bail!("unknown argument `{}`", other),
        }
    }

    match command.as_str() {
        "generate-keybindings-doc" => {
            let contents = render_keybindings_doc();
            write_or_check(
                &docs_keybindings_path()?,
                &contents,
                check_only,
                "keybindings docs",
            )
        }
        "generate-config-doc" => {
            let config_doc = render_configuration_doc();
            let default_template = render_default_config_template();
            write_or_check(
                &docs_configuration_path()?,
                &config_doc,
                check_only,
                "configuration docs",
            )?;
            write_or_check(
                &default_config_template_path()?,
                &default_template,
                check_only,
                "default config template",
            )
        }
        other => bail!(
            "unknown xtask command `{}`; expected `generate-keybindings-doc` or `generate-config-doc`",
            other
        ),
    }
}

fn write_or_check(path: &Path, contents: &str, check_only: bool, label: &str) -> Result<()> {
    if check_only {
        let existing = std::fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        if existing == contents {
            println!("{} are up to date", label);
            return Ok(());
        }
        bail!(
            "{} are out of date; run `cargo run -p xtask -- {}`",
            label,
            if label == "keybindings docs" {
                "generate-keybindings-doc"
            } else {
                "generate-config-doc"
            }
        );
    }

    std::fs::write(path, contents)
        .with_context(|| format!("failed to write {}", path.display()))?;
    println!("updated {}", path.display());
    Ok(())
}

fn docs_keybindings_path() -> Result<PathBuf> {
    Ok(workspace_root()?.join("docs/keybindings.md"))
}

fn docs_configuration_path() -> Result<PathBuf> {
    Ok(workspace_root()?.join("docs/configuration.md"))
}

fn default_config_template_path() -> Result<PathBuf> {
    Ok(workspace_root()
        .with_context(|| "workspace root")?
        .join("crates/config_core/src/default_config.txt"))
}

fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .context("failed to compute workspace root")
}

fn render_keybindings_doc() -> String {
    let mut output = String::new();

    output.push_str("# Keybindings\n\n");
    output.push_str("_This file is generated by `cargo run -p xtask -- generate-keybindings-doc`. Do not edit manually._\n\n");
    output.push_str("Termy keybindings use Ghostty-style trigger overrides via repeated `keybind` lines in `~/.config/termy/config.txt`.\n\n");

    output.push_str("## Default Keybinds\n\n");
    for platform in KeybindPlatform::ALL {
        output.push_str(&format!("### {}\n\n", platform_title(platform)));
        for binding in default_keybinds_for_platform(platform) {
            let tmux_note = tmux_action_note(binding.action);
            output.push_str(&format!(
                "- `{}` -> `{}`{}\n",
                binding.trigger,
                binding.action.config_name(),
                tmux_note,
            ));
        }
        output.push('\n');
    }

    output.push_str("`secondary` maps to `cmd` on macOS and `ctrl` on non-macOS platforms.\n\n");
    output.push_str("Notes:\n\n");
    output.push_str("- `toggle_agent_sidebar` is bound by default, but it only works when `agent_sidebar_enabled = true` in `~/.config/termy/config.txt`.\n");
    output.push_str("- `toggle_vertical_tab_sidebar` only works when `vertical_tabs = true`; enable it in Settings > Tabs or in `~/.config/termy/config.txt`.\n\n");

    output.push_str("## Config Syntax\n\n");
    output.push_str("Supported forms:\n\n");
    output.push_str("- `keybind = clear`\n");
    output.push_str("- `keybind = <trigger>=<action>`\n");
    output.push_str("- `keybind = <trigger>=unbind`\n\n");
    output.push_str("Behavior:\n\n");
    output.push_str("- Directives are applied in file order.\n");
    output.push_str("- Later lines win for the same trigger.\n");
    output.push_str("- `clear` removes all defaults before later lines are applied.\n");
    output.push_str("- `unbind` removes the current mapping for a trigger.\n");
    output.push_str("- Invalid lines are ignored (with warnings).\n\n");

    output.push_str("Related UI option:\n\n");
    output.push_str("- `command_palette_show_keybinds = true|false` controls whether command palette rows show shortcut badges.\n\n");

    output.push_str("## Configurable Actions\n\n");
    for action in CommandId::all() {
        output.push_str(&format!(
            "- `{}`{}\n",
            action.config_name(),
            tmux_action_note(action)
        ));
    }

    output.push_str("\n## Customization Examples\n\n");
    output.push_str("### 1) Override one default\n\n");
    output.push_str("```txt\nkeybind = cmd-p=toggle_command_palette\n```\n\n");
    output.push_str("### 2) Remove one default\n\n");
    output.push_str("```txt\nkeybind = cmd-w=unbind\n```\n\n");
    output.push_str("### 3) Start from scratch\n\n");
    output.push_str("```txt\nkeybind = clear\nkeybind = cmd-p=toggle_command_palette\nkeybind = cmd-t=new_tab\nkeybind = cmd-w=close_pane_or_tab\nkeybind = cmd-c=copy\nkeybind = cmd-v=paste\n```\n\n");
    output.push_str("### 4) Use `secondary` for cross-platform configs\n\n");
    output.push_str("```txt\nkeybind = secondary-p=toggle_command_palette\nkeybind = secondary-t=new_tab\n```\n");

    output
}

fn render_configuration_doc() -> String {
    let defaults = AppConfig::default();
    let mut output = String::new();

    output.push_str("# Configuration\n\n");
    output.push_str("_This file is generated by `cargo run -p xtask -- generate-config-doc`. Do not edit manually._\n\n");
    output.push_str("Termy reads configuration from `~/.config/termy/config.txt`.\n\n");
    output.push_str("Tmux integration is an add-on. Set `tmux_enabled = true` to start in tmux mode by default. Use `tmux Sessions…` from the command palette or File menu to attach, switch, create, and manage sessions at runtime.\n\n");

    for section in [
        SettingsSection::Appearance,
        SettingsSection::Terminal,
        SettingsSection::Tabs,
        SettingsSection::Advanced,
        SettingsSection::Keybindings,
    ] {
        output.push_str(&format!("## {}\n\n", section.label()));
        for spec in root_setting_specs()
            .iter()
            .filter(|spec| spec.section == section)
        {
            output.push_str(&format!("`{}`\n", spec.key));
            output.push_str(&format!(
                "- Default: {}\n",
                root_default_display(&defaults, spec.id)
            ));
            if !spec.aliases.is_empty() {
                output.push_str(&format!("- Aliases: `{}`\n", spec.aliases.join("`, `")));
            }
            output.push_str(&format!("- {}\n", spec.description));
            output.push_str(&format!("- Group: `{}`\n\n", spec.group));
        }
    }

    output.push_str(&render_task_docs(TaskDocsFormat::Markdown));

    output.push_str("## Colors\n\n");
    output.push_str("Use `[colors]` to override theme colors with `#RRGGBB` values.\n\n");
    for spec in color_setting_specs() {
        output.push_str(&format!("`{}`\n", spec.key));
        if !spec.aliases.is_empty() {
            output.push_str(&format!("- Aliases: `{}`\n", spec.aliases.join("`, `")));
        }
        output.push_str(&format!("- {}\n\n", spec.description));
    }

    output
}

fn root_default_display(defaults: &AppConfig, id: RootSettingId) -> String {
    match id {
        RootSettingId::WorkingDirFallback => {
            "`home` (macOS/Windows), `process` (Linux/other)".to_string()
        }
        RootSettingId::Keybind => "built-in platform defaults".to_string(),
        _ => root_setting_default_value(defaults, id)
            .map(|value| format!("`{}`", value))
            .unwrap_or_else(|| "unset".to_string()),
    }
}

fn render_default_config_template() -> String {
    let defaults = AppConfig::default();
    let mut output = String::new();
    output.push_str("# Main settings\n");

    for spec in root_setting_specs() {
        if spec.id == RootSettingId::Keybind {
            continue;
        }
        output.push_str(&format!("# {}\n", spec.description));

        let should_comment = matches!(
            spec.id,
            RootSettingId::WorkingDir
                | RootSettingId::WorkingDirFallback
                | RootSettingId::InactiveTabScrollback
        );

        let value = match spec.id {
            RootSettingId::WorkingDirFallback => "home".to_string(),
            _ => {
                root_setting_default_value(&defaults, spec.id).unwrap_or_else(|| "none".to_string())
            }
        };

        if should_comment {
            output.push_str(&format!("# {} = {}\n", spec.key, value));
        } else {
            output.push_str(&format!("{} = {}\n", spec.key, value));
        }
    }

    output.push_str("\n# Keybindings (repeatable)\n");
    output.push_str("# keybind = cmd-p=toggle_command_palette\n");
    output.push_str("# keybind = cmd-c=copy\n");
    output.push_str("# keybind = cmd-c=unbind\n");
    output.push_str("# keybind = clear\n");
    output.push_str("# keybind = secondary-alt-shift-left=resize_pane_left\n");
    output.push_str(&render_task_docs(TaskDocsFormat::Template));

    output.push_str("\n# Color overrides\n");
    output.push_str("[colors]\n");
    for spec in color_setting_specs() {
        let placeholder = match spec.id {
            ColorSettingId::Foreground => "#e7ebf5",
            ColorSettingId::Background => "#0b1020",
            ColorSettingId::Cursor => "#a7e9a3",
            _ => "#000000",
        };
        output.push_str(&format!("# {} = {}\n", spec.key, placeholder));
    }

    output
}

const TASK_FIELD_DOCS: &[(&str, &str)] = &[
    ("command", "(required): shell command to run in a new tab"),
    (
        "layout",
        "(optional): only show the task when that saved layout is active",
    ),
    (
        "working_dir",
        "(optional): working directory for the launched tab",
    ),
];

const TASK_EXAMPLE_LINES: &[&str] = &[
    "task.build.command = cargo build",
    "task.build.working_dir = crates/cli",
    "task.dev_server.layout = dashboard",
    "task.dev_server.command = cargo run",
];

#[derive(Clone, Copy)]
enum TaskDocsFormat {
    Markdown,
    Template,
}

fn render_task_docs(format: TaskDocsFormat) -> String {
    let mut output = String::new();
    match format {
        TaskDocsFormat::Markdown => {
            output.push_str("## Tasks\n\n");
            output.push_str(
                "Tasks are configured with repeatable root keys using the pattern `task.<name>.<field>`.\n\n",
            );
            output.push_str("Supported fields:\n\n");
            for (field, description) in TASK_FIELD_DOCS {
                output.push_str(&format!("- `task.<name>.{field}` {description}\n"));
            }
            output.push_str("\nExample:\n\n```txt\n");
            for line in TASK_EXAMPLE_LINES {
                output.push_str(line);
                output.push('\n');
            }
            output.push_str("```\n\n");
        }
        TaskDocsFormat::Template => {
            output.push_str("\n# Tasks (repeatable)\n");
            output.push_str("# Tasks use the pattern task.<name>.<field>\n");
            output.push_str("# Supported fields:\n");
            for (field, description) in TASK_FIELD_DOCS {
                output.push_str(&format!("# - task.<name>.{field} {description}\n"));
            }
            output.push_str("# Example:\n");
            for line in TASK_EXAMPLE_LINES {
                output.push_str(&format!("# {line}\n"));
            }
        }
    }
    output
}

fn platform_title(platform: KeybindPlatform) -> &'static str {
    match platform {
        KeybindPlatform::MacOs => "macOS Defaults",
        KeybindPlatform::Windows => "Windows Defaults",
        KeybindPlatform::Linux => "Linux Defaults",
        KeybindPlatform::Other => "Other Platform Defaults",
    }
}

fn tmux_action_note(action: CommandId) -> &'static str {
    if action.is_tmux_only() {
        " (tmux required)"
    } else {
        ""
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keybindings_doc_lists_resize_without_tmux_marker() {
        let out = render_keybindings_doc();
        assert!(out.contains("resize_pane_left`"));
        assert!(!out.contains("resize_pane_left` (tmux required)"));
        assert!(out.contains("toggle_command_palette`"));
    }

    #[test]
    fn keybindings_doc_notes_disabled_sidebar_shortcuts() {
        let out = render_keybindings_doc();
        assert!(out.contains("agent_sidebar_enabled = true"));
        assert!(out.contains("vertical_tabs = true"));
    }

    #[test]
    fn configuration_doc_mentions_runtime_tmux_session_hub() {
        let out = render_configuration_doc();
        assert!(out.contains("Tmux integration is an add-on"));
        assert!(out.contains("attach, switch, create, and manage sessions at runtime"));
    }

    #[test]
    fn default_config_template_includes_task_field_reference() {
        let out = render_default_config_template();
        assert!(out.contains("# Supported fields:"));
        assert!(
            out.contains("# - task.<name>.command (required): shell command to run in a new tab")
        );
        assert!(out.contains("# task.dev_server.command = cargo run"));
    }
}
