import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const wasmPath = resolve(packageRoot, 'wasm/termy_wasm_bg.wasm')
const glueInputPath = resolve(packageRoot, 'wasm/termy_wasm.js')
const glueTypesInputPath = resolve(packageRoot, 'wasm/termy_wasm.d.ts')
const bytesOutputPath = resolve(packageRoot, 'src/generated/wasm-bytes.ts')
const glueOutputPath = resolve(packageRoot, 'src/generated/termy-wasm.js')
const glueTypesOutputPath = resolve(packageRoot, 'src/generated/termy-wasm.d.ts')

const bytes = await readFile(wasmPath)
const base64 = bytes.toString('base64')
const chunks = base64.match(/.{1,96}/g) ?? []
const glueSource = await patchedGlueSource()
const glueTypes = await readFile(glueTypesInputPath, 'utf8')

await mkdir(dirname(bytesOutputPath), { recursive: true })
await writeFile(
  bytesOutputPath,
  `// Generated by scripts/embed-wasm.mjs. Do not edit.\n` +
    `\n` +
    `let cachedWasmBytes: Uint8Array | undefined\n` +
    `\n` +
    `const wasmBase64 = [\n` +
    chunks.map((chunk) => `  '${chunk}',`).join('\n') +
    `\n].join('')\n` +
    `\n` +
    `export function embeddedWasmBytes(): Uint8Array {\n` +
    `  cachedWasmBytes ??= decodeBase64(wasmBase64)\n` +
    `  return cachedWasmBytes\n` +
    `}\n` +
    `\n` +
    `function decodeBase64(value: string): Uint8Array {\n` +
    `  const decode = typeof globalThis.atob === 'function' ? globalThis.atob.bind(globalThis) : nodeAtob\n` +
    `  const binary = decode(value)\n` +
    `  const bytes = new Uint8Array(binary.length)\n` +
    `\n` +
    `  for (let index = 0; index < binary.length; index += 1) {\n` +
    `    bytes[index] = binary.charCodeAt(index)\n` +
    `  }\n` +
    `\n` +
    `  return bytes\n` +
    `}\n` +
    `\n` +
    `function nodeAtob(value: string): string {\n` +
    `  const candidate = globalThis as {\n` +
    `    Buffer?: {\n` +
    `      from(input: string, encoding: 'base64'): { toString(encoding: 'binary'): string }\n` +
    `    }\n` +
    `  }\n` +
    `\n` +
    `  if (!candidate.Buffer) {\n` +
    `    throw new Error('libtermy.js could not decode embedded WASM bytes in this runtime')\n` +
    `  }\n` +
    `\n` +
    `  return candidate.Buffer.from(value, 'base64').toString('binary')\n` +
    `}\n`,
)
await writeFile(glueOutputPath, glueSource)
await writeFile(glueTypesOutputPath, glueTypes)

console.log(`Embedded ${bytes.byteLength} WASM bytes into ${bytesOutputPath}`)

async function patchedGlueSource() {
  const source = await readFile(glueInputPath, 'utf8')
  const fallbackLine = "        module_or_path = new URL('termy_wasm_bg.wasm', import.meta.url);"

  if (!source.includes(fallbackLine)) {
    throw new Error(`Could not find wasm-bindgen fallback URL in ${glueInputPath}`)
  }

  return source
    .replace(
      '/* @ts-self-types="./termy_wasm.d.ts" */',
      '/* @ts-self-types="./termy-wasm.d.ts" */',
    )
    .replace(
      fallbackLine,
      "        throw new Error('libtermy.js bundled WASM init requires embedded bytes');",
    )
}
