/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ReleasesIndexRouteImport } from "./routes/releases/index"
import { Route as ReleasesTagRouteImport } from "./routes/releases/$tag"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: "/releases/",
  path: "/releases/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesTagRoute = ReleasesTagRouteImport.update({
  id: "/releases/$tag",
  path: "/releases/$tag",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/releases/": typeof ReleasesIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/releases": typeof ReleasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/releases/": typeof ReleasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/releases/$tag" | "/releases/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/releases/$tag" | "/releases"
  id: "__root__" | "/" | "/releases/$tag" | "/releases/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReleasesTagRoute: typeof ReleasesTagRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/releases/": {
      id: "/releases/"
      path: "/releases"
      fullPath: "/releases/"
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/releases/$tag": {
      id: "/releases/$tag"
      path: "/releases/$tag"
      fullPath: "/releases/$tag"
      preLoaderRoute: typeof ReleasesTagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReleasesTagRoute: ReleasesTagRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
