/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DeviceRouteImport } from "./routes/device"
import { Route as AddRouteImport } from "./routes/add"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ThemesIndexRouteImport } from "./routes/themes/index"
import { Route as ReleasesIndexRouteImport } from "./routes/releases/index"
import { Route as DocsIndexRouteImport } from "./routes/docs/index"
import { Route as ContributorsIndexRouteImport } from "./routes/contributors/index"
import { Route as ThemesStudioRouteImport } from "./routes/themes/studio"
import { Route as ThemesAddRouteImport } from "./routes/themes/add"
import { Route as ThemesSlugRouteImport } from "./routes/themes/$slug"
import { Route as ReleasesTagRouteImport } from "./routes/releases/$tag"
import { Route as DocsSplatRouteImport } from "./routes/docs/$"
import { Route as ThemesSlugUpdateRouteImport } from "./routes/themes/$slug/update"

const DeviceRoute = DeviceRouteImport.update({
  id: "/device",
  path: "/device",
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: "/add",
  path: "/add",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: "/themes/",
  path: "/themes/",
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: "/releases/",
  path: "/releases/",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/docs/",
  path: "/docs/",
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsIndexRoute = ContributorsIndexRouteImport.update({
  id: "/contributors/",
  path: "/contributors/",
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesStudioRoute = ThemesStudioRouteImport.update({
  id: "/themes/studio",
  path: "/themes/studio",
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesAddRoute = ThemesAddRouteImport.update({
  id: "/themes/add",
  path: "/themes/add",
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: "/themes/$slug",
  path: "/themes/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesTagRoute = ReleasesTagRouteImport.update({
  id: "/releases/$tag",
  path: "/releases/$tag",
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/docs/$",
  path: "/docs/$",
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugUpdateRoute = ThemesSlugUpdateRouteImport.update({
  id: "/update",
  path: "/update",
  getParentRoute: () => ThemesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/add": typeof AddRoute
  "/device": typeof DeviceRoute
  "/docs/$": typeof DocsSplatRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/themes/$slug": typeof ThemesSlugRouteWithChildren
  "/themes/add": typeof ThemesAddRoute
  "/themes/studio": typeof ThemesStudioRoute
  "/contributors/": typeof ContributorsIndexRoute
  "/docs/": typeof DocsIndexRoute
  "/releases/": typeof ReleasesIndexRoute
  "/themes/": typeof ThemesIndexRoute
  "/themes/$slug/update": typeof ThemesSlugUpdateRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/add": typeof AddRoute
  "/device": typeof DeviceRoute
  "/docs/$": typeof DocsSplatRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/themes/$slug": typeof ThemesSlugRouteWithChildren
  "/themes/add": typeof ThemesAddRoute
  "/themes/studio": typeof ThemesStudioRoute
  "/contributors": typeof ContributorsIndexRoute
  "/docs": typeof DocsIndexRoute
  "/releases": typeof ReleasesIndexRoute
  "/themes": typeof ThemesIndexRoute
  "/themes/$slug/update": typeof ThemesSlugUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/add": typeof AddRoute
  "/device": typeof DeviceRoute
  "/docs/$": typeof DocsSplatRoute
  "/releases/$tag": typeof ReleasesTagRoute
  "/themes/$slug": typeof ThemesSlugRouteWithChildren
  "/themes/add": typeof ThemesAddRoute
  "/themes/studio": typeof ThemesStudioRoute
  "/contributors/": typeof ContributorsIndexRoute
  "/docs/": typeof DocsIndexRoute
  "/releases/": typeof ReleasesIndexRoute
  "/themes/": typeof ThemesIndexRoute
  "/themes/$slug/update": typeof ThemesSlugUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/add"
    | "/device"
    | "/docs/$"
    | "/releases/$tag"
    | "/themes/$slug"
    | "/themes/add"
    | "/themes/studio"
    | "/contributors/"
    | "/docs/"
    | "/releases/"
    | "/themes/"
    | "/themes/$slug/update"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/add"
    | "/device"
    | "/docs/$"
    | "/releases/$tag"
    | "/themes/$slug"
    | "/themes/add"
    | "/themes/studio"
    | "/contributors"
    | "/docs"
    | "/releases"
    | "/themes"
    | "/themes/$slug/update"
  id:
    | "__root__"
    | "/"
    | "/add"
    | "/device"
    | "/docs/$"
    | "/releases/$tag"
    | "/themes/$slug"
    | "/themes/add"
    | "/themes/studio"
    | "/contributors/"
    | "/docs/"
    | "/releases/"
    | "/themes/"
    | "/themes/$slug/update"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  DeviceRoute: typeof DeviceRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ReleasesTagRoute: typeof ReleasesTagRoute
  ThemesSlugRoute: typeof ThemesSlugRouteWithChildren
  ThemesAddRoute: typeof ThemesAddRoute
  ThemesStudioRoute: typeof ThemesStudioRoute
  ContributorsIndexRoute: typeof ContributorsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/device": {
      id: "/device"
      path: "/device"
      fullPath: "/device"
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/add": {
      id: "/add"
      path: "/add"
      fullPath: "/add"
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/themes/": {
      id: "/themes/"
      path: "/themes"
      fullPath: "/themes/"
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/releases/": {
      id: "/releases/"
      path: "/releases"
      fullPath: "/releases/"
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/": {
      id: "/docs/"
      path: "/docs"
      fullPath: "/docs/"
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contributors/": {
      id: "/contributors/"
      path: "/contributors"
      fullPath: "/contributors/"
      preLoaderRoute: typeof ContributorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/themes/studio": {
      id: "/themes/studio"
      path: "/themes/studio"
      fullPath: "/themes/studio"
      preLoaderRoute: typeof ThemesStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/themes/add": {
      id: "/themes/add"
      path: "/themes/add"
      fullPath: "/themes/add"
      preLoaderRoute: typeof ThemesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/themes/$slug": {
      id: "/themes/$slug"
      path: "/themes/$slug"
      fullPath: "/themes/$slug"
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/releases/$tag": {
      id: "/releases/$tag"
      path: "/releases/$tag"
      fullPath: "/releases/$tag"
      preLoaderRoute: typeof ReleasesTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/docs/$": {
      id: "/docs/$"
      path: "/docs/$"
      fullPath: "/docs/$"
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/themes/$slug/update": {
      id: "/themes/$slug/update"
      path: "/update"
      fullPath: "/themes/$slug/update"
      preLoaderRoute: typeof ThemesSlugUpdateRouteImport
      parentRoute: typeof ThemesSlugRoute
    }
  }
}

interface ThemesSlugRouteChildren {
  ThemesSlugUpdateRoute: typeof ThemesSlugUpdateRoute
}

const ThemesSlugRouteChildren: ThemesSlugRouteChildren = {
  ThemesSlugUpdateRoute: ThemesSlugUpdateRoute,
}

const ThemesSlugRouteWithChildren = ThemesSlugRoute._addFileChildren(
  ThemesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  DeviceRoute: DeviceRoute,
  DocsSplatRoute: DocsSplatRoute,
  ReleasesTagRoute: ReleasesTagRoute,
  ThemesSlugRoute: ThemesSlugRouteWithChildren,
  ThemesAddRoute: ThemesAddRoute,
  ThemesStudioRoute: ThemesStudioRoute,
  ContributorsIndexRoute: ContributorsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  ThemesIndexRoute: ThemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
